### PR TITLE
Remove not required stuff from installation script

### PR DESCRIPTION
**Pull request by pascalberger**
Cleanup some stuff:
* There's currently no difference between local and remote paths.
* The `*_trans* variables seem to be not used.
* The `killexec` block will never be called
* The log file is not used by the Chocolatey helper

### CODE REVIEW

**Comment by pascalberger** [comment]
@marcinbojko I added the local/remote and trans stuff back in. 

I don't know the Puppet Chocolatey provider but the current implementation doesn't really makes much sense to me as eg. it will only work for the x68 version. And any reason why not just implement this through package parameters?

**Comment by marcinbojko** [comment]
Hi @pascalberger 
As you can see, all my modules are 'generic' and prepared to have 86/64 version, local and remote paths as well.
So I really see no need to change it for one specific package.

**Comment by pascalberger** [comment]
@marcinbojko I already made the requested changes. Do you require more changes or otherwise I will close this PR.

**Comment by marcinbojko** [comment]
@pascalberger  
I just found that this repo is outdated as hell, and not a real package repo - my fault.
When I became maintainer I've created a fresh repo called 'webdeploy' - and THAT repo is real package repo.
So I am going to close this repo and open a new one.
If you take look inside real choco package you'll see the difference.
Sorry for the confusion.

**Comment by pascalberger** [comment]
@marcinbojko The [current Chocolatey package](https://chocolatey.org/packages/webdeploy) links to https://github.com/marcinbojko/webdeploy which does not exist

**Comment by marcinbojko** [comment]
@pascalberger 
That's what I am talking about. This repo will be closed, and new repo will be open.

**Pull request closed without merging**
